### ISSUE TITLE
Please add ability of installing the application using helm chart

### ISSUE THREAD

**Issue by yuripastushenko** [flant/k8s-image-availability-exporter#13]
We would like to have the availability to install this application using helm chart.
Will be great if the helm chart will be customizable.
Also, considering that prometheus operator is the main tool for monitoring and alerting in kubernetes clusters, will be great to add the support of its custom resources creation, through this chart, like it is done on other public charts. 
For example:
- https://github.com/helm/charts/blob/master/stable/envoy
- https://github.com/helm/charts/tree/master/stable/elasticsearch-exporter
- https://github.com/helm/charts/tree/master/stable/rabbitmq-ha

We suppose to add alerts and service monitors through this chart.
And will be great to change the podMonitor to serviceMonitor, as it better fit to this situation.

**Comment by shurup** [comment]
Thank you very much for your issue! It all sounds really reasonable. Sadly we can't promise implementing it right now. If you need it ASAP, please welcome to make relevant PRs (we're happy to help with everything). Otherwise, we'll be back to these ideas when we have more time.

**Comment by yuripastushenko** [comment]
@shurup can you please review the pull request?

**Comment by yuripastushenko** [comment]
@zuzzas Do you have any helm chart repository?
We would like to install this application in the following way:
```
helm repo add flant https//path-to-helm-chart-repository
```

**Comment by yuripastushenko** [comment]
Added new issue about that - https://github.com/flant/k8s-image-availability-exporter/issues/19
