### ISSUE TITLE
Add ability to install the application from helm chart repository

### ISSUE THREAD

**Issue by yuripastushenko** [flant/k8s-image-availability-exporter#19]
Hello!
We would like to install this application from our CI.
Will be great if we can install it like other popular public application, from helm chart repository.
Ex:
```
helm repo add flant https//path-to-helm-chart-repository
helm install flant/k8s-image-availability-exporter
```

**Comment by evgkrsk** [comment]
Seems fixed in https://github.com/flant/helm-charts/tree/master/.helm/charts/k8s-image-availability-exporter

**Comment by shurup** [comment]
Right, thanks for pointing out! There was a duplicate #30 on this issue.
