### ISSUE TITLE
Publish helm chart to helm registry

### ISSUE THREAD

**Issue by Nitive** [flant/k8s-image-availability-exporter#30]
Please publish helm chart to publicly available helm registry. The easiest way is to use GitHub Pages and official [GitHub action helm/chart-releaser-action](https://github.com/helm/chart-releaser-action).

I'm ready to add a workflow and create a PR if you like

**Comment by shurup** [comment]
Hi @Nitive and thank you for your idea! The chart for k8s-iae is now published via [our public ChartMuseum](https://github.com/flant/helm-charts). Please let me know if that works for you.

**Comment by Nitive** [comment]
Great, thank you!
